### ISSUE TITLE
Show medicines

### ISSUE THREAD

**Issue by leticamps** [marinagot/MyFirstAidKitJ#2]
Mostrar medicinas en el panel

**Comment by leticamps** [comment]
Cosas para hacer:

- [x] Aprender a mostrar listas


- [x] Extraer las medicinas en forma de lista de la base de datos

- [x] Conseguir visualizar la lista en el home
- [ ] Plantear si ante medicinas caducadas se eliminan las medicinas, no se visualizan o aparecen con una seleccion especial

- [ ]  Crear una issue nueva para editar/eliminar medicinas

**Comment by itum95** [comment]
- [ ] Crear una issue nueva para editar/eliminar medicinas

**Comment by John-Development** [comment]
Cerrada pese a que no se han planteado los dos ultimos puntos (aún pendiente)
