### ISSUE TITLE
Calendario no funciona bien en agregar medicina

### ISSUE THREAD

**Issue by John-Development** [marinagot/MyFirstAidKitJ#5]
Cuando se inserta una nueva medicina que caduca en el día actual, si no se cambia la fecha del calendario (que tiene por defecto seleccionado el dia actual) pide que se rellenen todos los campos

**Comment by marinagot** [comment]
http://www.androidcurso.com/index.php/485
Aquí te dice cómo usarlo desde la clase java sin crearte un elemento calendario en layout.xml

**Comment by marinagot** [comment]
arreglado y añadido calendario en medicine_edit, treatment_edit y birthday
